### ISSUE TITLE
jacoco can not work.

### ISSUE THREAD

**Issue by pw0rld** [codingsoo/REST_Go#5]
I am having trouble setting up this experiment on my local machine. Specifically, I am encountering an error when attempting to run the proxyprint service. (It's not just proxyprint, it looks like `jacoco.agent` is having problems)

```
java.io.IOException: Invalid execution data file.
        at org.jacoco.agent.rt.internal_3570298.core.data.ExecutionDataReader.read(ExecutionDataReader.java:90)
        at org.jacoco.agent.rt.internal_3570298.output.TcpConnection.run(TcpConnection.java:60)
        at org.jacoco.agent.rt.internal_3570298.output.TcpServerOutput$1.run(TcpServerOutput.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.io.IOException: Invalid execution data file.
        at org.jacoco.agent.rt.internal_3570298.core.data.ExecutionDataReader.read(ExecutionDataReader.java:90)
        at org.jacoco.agent.rt.internal_3570298.output.TcpConnection.run(TcpConnection.java:60)
        at org.jacoco.agent.rt.internal_3570298.output.TcpServerOutput$1.run(TcpServerOutput.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.io.IOException: Invalid execution data file.
        at org.jacoco.agent.rt.internal_3570298.core.data.ExecutionDataReader.read(ExecutionDataReader.java:90)
        at org.jacoco.agent.rt.internal_3570298.output.TcpConnection.run(TcpConnection.java:60)
        at org.jacoco.agent.rt.internal_3570298.output.TcpServerOutput$1.run(TcpServerOutput.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.io.IOException: Invalid execution data file.
        at org.jacoco.agent.rt.internal_3570298.core.data.ExecutionDataReader.read(ExecutionDataReader.java:90)
        at org.jacoco.agent.rt.internal_3570298.output.TcpConnection.run(TcpConnection.java:60)
        at org.jacoco.agent.rt.internal_3570298.output.TcpServerOutput$1.run(TcpServerOutput.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.io.IOException: Invalid execution data file.
        at org.jacoco.agent.rt.internal_3570298.core.data.ExecutionDataReader.read(ExecutionDataReader.java:90)
        at org.jacoco.agent.rt.internal_3570298.output.TcpConnection.run(TcpConnection.java:60)
        at org.jacoco.agent.rt.internal_3570298.output.TcpServerOutput$1.run(TcpServerOutput.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.io.IOException: Invalid execution data file.
        at org.jacoco.agent.rt.internal_3570298.core.data.ExecutionDataReader.read(ExecutionDataReader.java:90)
        at org.jacoco.agent.rt.internal_3570298.output.TcpConnection.run(TcpConnection.java:60)
        at org.jacoco.agent.rt.internal_3570298.output.TcpServerOutput$1.run(TcpServerOutput.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.io.IOException: Invalid execution data file.
        at org.jacoco.agent.rt.internal_3570298.core.data.ExecutionDataReader.read(ExecutionDataReader.java:90)
        at org.jacoco.agent.rt.internal_3570298.output.TcpConnection.run(TcpConnection.java:60)
        at org.jacoco.agent.rt.internal_3570298.output.TcpServerOutput$1.run(TcpServerOutput.java:64)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
Could you please provide me with some guidance on how to resolve this issue? Any help would be greatly appreciated.

Thank you.

**Comment by codingsoo** [comment]
Hi pw0rld,

Can you give me more context to reproduce the error? (e.g., set of commands to reproduce the error)

**Comment by codingsoo** [comment]
I've updated the coverage measuring part. Please try with the new description and open this issue if you have any problem!
